# Generated by Django 2.1.2 on 2018-11-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
