# Generated by Django 2.1.2 on 2018-11-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.DateField(default=None, null=True),
        ),
    ]
