# Generated by Django 2.1.2 on 2018-11-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20181103_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='contents',
            field=models.TextField(default='', null=True),
        ),
    ]
