# Generated by Django 2.1.2 on 2018-11-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_todo_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='contents',
            field=models.TextField(default=None, null=True),
        ),
    ]
